# Generated by Django 5.2.6 on 2025-09-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_book', '0001_initial'),
        ('my_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='library_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('lib_code', models.IntegerField()),
                ('city', models.CharField()),
                ('book', models.ManyToManyField(related_name='book', to='my_book.book_list')),
                ('user', models.ManyToManyField(related_name='user', to='my_user.user')),
            ],
        ),
    ]
