# Generated by Django 5.2.6 on 2025-09-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0006_alter_book_list_library_alter_book_list_user'),
        ('my_library', '0001_initial'),
        ('my_user', '0005_remove_user_library_user_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_list',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='book', to='my_book.book_list'),
        ),
        migrations.AlterField(
            model_name='library_list',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to='my_user.user'),
        ),
    ]
