# Generated by Django 5.2.6 on 2025-09-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('pers_id', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('pers_code', models.IntegerField()),
            ],
        ),
    ]
