# Generated by Django 5.2.6 on 2025-09-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0001_initial'),
        ('my_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='my_lib', to='my_library.library_list'),
            preserve_default=False,
        ),
    ]
