# Generated by Django 5.2.6 on 2025-09-16 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0002_book_list_library'),
        ('my_user', '0002_user_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='my_book', to='my_book.book_list'),
            preserve_default=False,
        ),
    ]
