# Generated by Django 5.2.6 on 2025-09-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0005_remove_book_list_user_book_list_user'),
        ('my_user', '0003_user_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='book',
        ),
        migrations.AddField(
            model_name='user',
            name='book',
            field=models.ManyToManyField(related_name='my_book', to='my_book.book_list'),
        ),
    ]
