# Generated by Django 5.2.6 on 2025-09-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0001_initial'),
        ('my_user', '0004_remove_user_book_user_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='library',
        ),
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.ManyToManyField(related_name='my_lib', to='my_library.library_list'),
        ),
    ]
