# Generated by Django 5.2.6 on 2025-09-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0006_alter_book_list_library_alter_book_list_user'),
        ('my_library', '0002_alter_library_list_book_alter_library_list_user'),
        ('my_user', '0005_remove_user_library_user_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_book', to='my_book.book_list'),
        ),
        migrations.AlterField(
            model_name='user',
            name='library',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_lib', to='my_library.library_list'),
        ),
    ]
