# Generated by Django 5.2.6 on 2025-09-16 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0002_book_list_library'),
        ('my_user', '0003_user_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_list',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_user', to='my_user.user'),
            preserve_default=False,
        ),
    ]
