# Generated by Django 5.2.6 on 2025-09-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0003_book_list_user'),
        ('my_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_list',
            name='library',
        ),
        migrations.AddField(
            model_name='book_list',
            name='library',
            field=models.ManyToManyField(related_name='lib', to='my_library.library_list'),
        ),
    ]
