# Generated by Django 5.2.6 on 2025-09-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0004_remove_book_list_library_book_list_library'),
        ('my_user', '0003_user_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_list',
            name='user',
        ),
        migrations.AddField(
            model_name='book_list',
            name='user',
            field=models.ManyToManyField(related_name='my_user', to='my_user.user'),
        ),
    ]
