# Generated by Django 5.2.6 on 2025-09-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0005_remove_book_list_user_book_list_user'),
        ('my_library', '0001_initial'),
        ('my_user', '0005_remove_user_library_user_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_list',
            name='library',
            field=models.ManyToManyField(blank=True, null=True, related_name='lib', to='my_library.library_list'),
        ),
        migrations.AlterField(
            model_name='book_list',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_user', to='my_user.user'),
        ),
    ]
