# Generated by Django 5.2.6 on 2025-09-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0006_alter_book_list_library_alter_book_list_user'),
        ('my_library', '0002_alter_library_list_book_alter_library_list_user'),
        ('my_user', '0006_alter_user_book_alter_user_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_list',
            name='wait_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='my_user_extra', to='my_user.user'),
        ),
        migrations.AlterField(
            model_name='book_list',
            name='library',
            field=models.ManyToManyField(blank=True, related_name='lib', to='my_library.library_list'),
        ),
        migrations.AlterField(
            model_name='book_list',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='my_user', to='my_user.user'),
        ),
    ]
